import type { Trader, FeedPost, Trade } from "./types"

export const SEED_TRADERS: Trader[] = [
  {
    id: "trader-sarah-chen",
    address: "GDSARAHCHEN7XLMTRADER2025TESTNETADDRESS",
    username: "@sarahchen",
    displayName: "Sarah Chen",
    avatar: "/professional-asian-woman-trader.jpg",
    bio: "Crypto trader since 2017. Specializing in momentum trading and technical analysis. Average 15% monthly returns.",
    verified: true,
    followers: 12500,
    following: 89,
    copiers: 3420,
    totalReturn: 245.8,
    winRate: 73.5,
    avgReturn: 15.2,
    riskScore: 6.5,
    totalTrades: 1247,
    successfulTrades: 917,
    portfolioValue: 450000,
    joinedDate: "2023-01-15",
    tags: ["Momentum", "Technical Analysis", "Day Trading"],
    stats: {
      totalVolume: 2500000,
      avgTradeSize: 2004,
      maxDrawdown: 12.5,
      sharpeRatio: 2.1,
      profitFactor: 1.85,
    },
  },
  {
    id: "trader-mike-rodriguez",
    address: "GDMIKEXLMTRADER2025RODRIGUEZ8TESTNETADD",
    username: "@mikerodriguez",
    displayName: "Mike Rodriguez",
    avatar: "/professional-latino-man-trader.jpg",
    bio: "Conservative swing trader focused on risk management. Building wealth slowly and steadily. 10% monthly avg.",
    verified: true,
    followers: 8900,
    following: 124,
    copiers: 2180,
    totalReturn: 187.3,
    winRate: 68.2,
    avgReturn: 10.5,
    riskScore: 4.2,
    totalTrades: 892,
    successfulTrades: 608,
    portfolioValue: 320000,
    joinedDate: "2023-03-22",
    tags: ["Swing Trading", "Risk Management", "Conservative"],
    stats: {
      totalVolume: 1800000,
      avgTradeSize: 2018,
      maxDrawdown: 8.3,
      sharpeRatio: 2.5,
      profitFactor: 2.1,
    },
  },
  {
    id: "trader-emma-watson",
    address: "GDEMMAWATSONXLMTRADER2025TESTNETADDRESS",
    username: "@emmawatson",
    displayName: "Emma Watson",
    avatar: "/professional-woman-blonde-trader.jpg",
    bio: "DeFi specialist and long-term holder. Focused on high-quality assets with 3-6 month holding periods.",
    verified: true,
    followers: 15200,
    following: 67,
    copiers: 4150,
    totalReturn: 312.5,
    winRate: 79.8,
    avgReturn: 22.3,
    riskScore: 5.8,
    totalTrades: 567,
    successfulTrades: 452,
    portfolioValue: 780000,
    joinedDate: "2022-11-08",
    tags: ["DeFi", "Long-term", "High Win Rate"],
    stats: {
      totalVolume: 3200000,
      avgTradeSize: 5644,
      maxDrawdown: 15.2,
      sharpeRatio: 1.9,
      profitFactor: 2.3,
    },
  },
]

export const SEED_POSTS: FeedPost[] = [
  {
    id: "post-sarah-1",
    traderId: "trader-sarah-chen",
    trader: SEED_TRADERS[0],
    content:
      "Just closed a position on XLM at +18% profit. The breakout above resistance was textbook. Technical analysis still works in 2025! 📈",
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    likes: 342,
    comments: 45,
    shares: 23,
    trade: {
      asset: "XLM",
      action: "SELL",
      amount: 50000,
      price: 0.42,
      profit: 18.2,
      timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    },
  },
  {
    id: "post-sarah-2",
    traderId: "trader-sarah-chen",
    trader: SEED_TRADERS[0],
    content:
      "Market analysis: Bitcoin hitting key support at $95k. Watching for a bounce or breakdown. My strategy? Waiting for confirmation before entry. Patience is key. 🎯",
    timestamp: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    likes: 521,
    comments: 89,
    shares: 41,
  },
  {
    id: "post-mike-1",
    traderId: "trader-mike-rodriguez",
    trader: SEED_TRADERS[1],
    content:
      "Conservative swing trade paying off. Entered SOL at $140, currently at $158. Setting trailing stop at +10%. Risk management > FOMO 🛡️",
    timestamp: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    likes: 287,
    comments: 34,
    shares: 18,
    trade: {
      asset: "SOL",
      action: "HOLD",
      amount: 2000,
      price: 158,
      profit: 12.9,
      timestamp: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    },
  },
  {
    id: "post-mike-2",
    traderId: "trader-mike-rodriguez",
    trader: SEED_TRADERS[1],
    content:
      "Reminder: Never risk more than 2% per trade. I've been trading for 3 years and this rule saved me countless times. Protect your capital first, profits second. 💪",
    timestamp: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    likes: 658,
    comments: 102,
    shares: 76,
  },
  {
    id: "post-emma-1",
    traderId: "trader-emma-watson",
    trader: SEED_TRADERS[2],
    content:
      "DeFi portfolio update: Up 28% this month. My long-term holdings in quality projects are finally paying off. This is why I don't day trade. 📊",
    timestamp: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    likes: 892,
    comments: 127,
    shares: 94,
    trade: {
      asset: "Multiple",
      action: "HOLD",
      amount: 150000,
      price: 0,
      profit: 28.0,
      timestamp: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    },
  },
  {
    id: "post-emma-2",
    traderId: "trader-emma-watson",
    trader: SEED_TRADERS[2],
    content:
      "Researching new DeFi protocols. Due diligence takes time but it's worth it. Looking at TVL, team background, audits, and tokenomics. Never rush into a position. 🔍",
    timestamp: new Date(Date.now() - 16 * 60 * 60 * 1000).toISOString(),
    likes: 421,
    comments: 67,
    shares: 32,
  },
]

export const SEED_STORIES = [
  {
    id: "story-sarah-1",
    traderId: "trader-sarah-chen",
    trader: SEED_TRADERS[0],
    type: "image" as const,
    content: "/trading-chart-analysis-technical-indicators.jpg",
    text: "Breaking: Major resistance broken! 🚀",
    timestamp: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    views: 2341,
  },
  {
    id: "story-mike-1",
    traderId: "trader-mike-rodriguez",
    trader: SEED_TRADERS[1],
    type: "text" as const,
    content:
      "Just hit my monthly profit target! Taking the rest of the week off. Remember: It's okay to step away from the screen.",
    timestamp: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    views: 1567,
  },
  {
    id: "story-emma-1",
    traderId: "trader-emma-watson",
    trader: SEED_TRADERS[2],
    type: "image" as const,
    content: "/crypto-portfolio-dashboard-gains.jpg",
    text: "Portfolio ATH! 🎉 Patience pays off",
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    views: 3892,
  },
]

export const SEED_TRADES: Trade[] = [
  {
    id: "trade-1",
    traderId: "trader-sarah-chen",
    trader: SEED_TRADERS[0],
    asset: "XLM",
    action: "BUY" as const,
    amount: 50000,
    price: 0.36,
    profit: 18.2,
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    status: "closed" as const,
  },
  {
    id: "trade-2",
    traderId: "trader-sarah-chen",
    trader: SEED_TRADERS[0],
    asset: "BTC",
    action: "BUY" as const,
    amount: 0.5,
    price: 95000,
    profit: -2.5,
    timestamp: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    status: "open" as const,
  },
  {
    id: "trade-3",
    traderId: "trader-mike-rodriguez",
    trader: SEED_TRADERS[1],
    asset: "SOL",
    action: "BUY" as const,
    amount: 2000,
    price: 140,
    profit: 12.9,
    timestamp: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    status: "open" as const,
  },
  {
    id: "trade-4",
    traderId: "trader-mike-rodriguez",
    trader: SEED_TRADERS[1],
    asset: "ETH",
    action: "SELL" as const,
    amount: 10,
    price: 3200,
    profit: 8.5,
    timestamp: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    status: "closed" as const,
  },
  {
    id: "trade-5",
    traderId: "trader-emma-watson",
    trader: SEED_TRADERS[2],
    asset: "USDC",
    action: "HOLD" as const,
    amount: 150000,
    price: 1.0,
    profit: 28.0,
    timestamp: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    status: "open" as const,
  },
  {
    id: "trade-6",
    traderId: "trader-emma-watson",
    trader: SEED_TRADERS[2],
    asset: "XLM",
    action: "BUY" as const,
    amount: 75000,
    price: 0.38,
    profit: 15.8,
    timestamp: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    status: "closed" as const,
  },
  {
    id: "trade-7",
    traderId: "trader-sarah-chen",
    trader: SEED_TRADERS[0],
    asset: "ADA",
    action: "BUY" as const,
    amount: 25000,
    price: 0.65,
    profit: 22.3,
    timestamp: new Date(Date.now() - 18 * 60 * 60 * 1000).toISOString(),
    status: "closed" as const,
  },
  {
    id: "trade-8",
    traderId: "trader-mike-rodriguez",
    trader: SEED_TRADERS[1],
    asset: "MATIC",
    action: "BUY" as const,
    amount: 15000,
    price: 0.85,
    profit: 5.2,
    timestamp: new Date(Date.now() - 20 * 60 * 60 * 1000).toISOString(),
    status: "open" as const,
  },
  {
    id: "trade-9",
    traderId: "trader-sarah-chen",
    trader: SEED_TRADERS[0],
    asset: "DOT",
    action: "SELL" as const,
    amount: 5000,
    price: 7.5,
    profit: 11.7,
    timestamp: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    status: "closed" as const,
  },
  {
    id: "trade-10",
    traderId: "trader-emma-watson",
    trader: SEED_TRADERS[2],
    asset: "AVAX",
    action: "BUY" as const,
    amount: 3000,
    price: 38.0,
    profit: 19.4,
    timestamp: new Date(Date.now() - 30 * 60 * 60 * 1000).toISOString(),
    status: "closed" as const,
  },
]
